### ISSUE TITLE
WebUI Password

### ISSUE THREAD

**Issue by irqnet** [glenndehaan/unifi-voucher-site#18]
I've just pulled the docker container from hub.docker and created the initial configurations to run the container.

What I'm struggling with is the password, requested on the website to create the voucher? Where can I find the env variable to configure it?

**Comment by glenndehaan** [comment]
Hey,

What you are looking for is the SECURITY_CODE please see: https://github.com/glenndehaan/unifi-voucher-site/blob/master/docker-compose.yml#L13

Hope this solves your problem

**Comment by irqnet** [comment]
Got it ;) Didn't identified env security_code as the web password, working for me now!

Thx a lot
