### ISSUE TITLE
config file?

### ISSUE THREAD

**Issue by aroundmyroom** [glenndehaan/unifi-voucher-site#20]
Just installed it without docker and its running, but wondering if I do miss the config file? cause in 2 files I had to change IP / site and at the end somewhere in the /modules/unifi.js the username / password. (and/or site / ip as well)

**Comment by glenndehaan** [comment]
No you are not missing a config file the application uses environment variables to configure itself. So you can just supply those when launching the app, the variables are described in the example docker compose file.

**Comment by aroundmyroom** [comment]
Ah clear .. 

for what's worth

#!/bin/bash
export UNIFI_IP='10.1.1.1'
export UNIFI_PORT='443'
export UNIFI_USERNAME='username'
export UNIFI_PASSWORD='password'
export UNIFI_SITE_ID='default'
export SECURITY_CODE='000'
export VOUCHER_TYPES='480,0,,,;1440,1,,,;10080,1,,,;525600,1,,,;'
export WEBPORT='80'
# export HTTPS='true'
# export SSL_CRT_FILE='/export/certificate/*.domain.cer'
# export SSL_KEY_FILE='/export/certificate/*.domain.key'
cd /home/unifi-voucher-site
/root/.nvm/versions/node/v19.3.0/bin/node server.js


Notes: npm start does not work with systemctl (I could not get it working)  so I start the application with node server.js. 
and now systemctl is working fine.

Would love to have support for SSL so that I can use my own certificates 

(using your script on a debian machine with npm 19 replacing my own ugly php script) ;)

**Comment by glenndehaan** [comment]
I would always recommend using a reverse proxy and not to expose the node process directly. The reverse proxy would then handle the SSL termination and could for example integrate with letsencrypt.

**Comment by aroundmyroom** [comment]
Agree and can do that I have nginx proxy manager running, but is unnecessary when you run this locally. It's not a strong need, but a nice to have ;)
