### ISSUE TITLE
font color of Voucher code 

### ISSUE THREAD

**Issue by aroundmyroom** [glenndehaan/unifi-voucher-site#21]
When accessing the application on an Iphone the colouring is changed during the evening to a black background.
But the code is not. It can be read but it is very dark grey so it is difficult to read in the screen.

![image](https://user-images.githubusercontent.com/250108/208262979-74c2dd2d-2fe5-4ec2-aeda-1b29ea12003f.png)
example

**Comment by glenndehaan** [comment]
Hey thanks for finding this issue. I'm usually on android so I didn't find this issue. I have pushed a fixed an tested in a webkit browser and it seems to be working now, can you confirm this after updating?

**Comment by aroundmyroom** [comment]
Will need some more testing, cause in the afternoon/evening it will turn black (no clue how my iphone is handling that, never investages), but now I see that the colour on iphone in the morning also is to vague

![image](https://user-images.githubusercontent.com/250108/208291826-45cb219c-34c3-4d88-9a58-c02c39079421.png)

**Comment by aroundmyroom** [comment]
on a PC it looks ok
![image](https://user-images.githubusercontent.com/250108/208291911-314dc847-3562-4637-a490-1786695268d2.png)

**Comment by glenndehaan** [comment]
The app is taking over the system preferred-color-scheme. In other words: Does the use have dark-mode enabled or not. It seems you have it set to auto currently. You should be able to switch that inside your device preferences to auto, light or dark.

Looking at the image you just send I think you need to clear the cache of the browser because it is loading the old CSS

**Comment by glenndehaan** [comment]
Oh also I forgot since you are running the code locally ensure you run the tailwind command again since this regenerates the CSS file

**Comment by glenndehaan** [comment]
You can verify if the new code is there to inspect the input field and look for the -webkit-text-fill-color property. If that is not there then the CSS has not been recompiled or you are stuck in some browser cache

<img width="479" alt="afbeelding" src="https://user-images.githubusercontent.com/7496187/208292377-a3910243-e0c1-48b4-a394-7930f0eef56b.png">

**Comment by aroundmyroom** [comment]
looks wierd under my windows with chrome

![image](https://user-images.githubusercontent.com/250108/208292908-2aab3a0a-46f2-4ffd-a83d-5a98a1b2ad6d.png)

looks different than from you and I did release cache and ran tailwinds

**Comment by glenndehaan** [comment]
No that looks fine. But you have to look for the CSS part

**Comment by glenndehaan** [comment]
Ahh wait, did you also can a npm ci before the tailwind command? Because a new module was added.

**Comment by glenndehaan** [comment]
This is basically the reason why I prefer people using the docker container since i'm remotely debugging one system

**Comment by aroundmyroom** [comment]
will check tonight. did a new pull and changes the way it was listening to my port 80 (variable in server.js) So its now default code again. Probably it will look fine tonight.

**Comment by aroundmyroom** [comment]
checked it, its readable, but still a little to grey-ish for my taste. But as nobody probably is giving tickets out by night it is fine ;)
