### ISSUE TITLE
Request:  Progress indicator

### ISSUE THREAD

**Issue by aroundmyroom** [glenndehaan/unifi-voucher-site#24]
When submitting a request for a voucher, when using on ie. a Cloudkey Gen2 plus it can take some time for the controller to react
See here:
The request is send at 7.43.21 and the person who requested the voucher had to wait for more than 30 seconds before there was an answer of API of the controller to get an voucher. 

So maybe you can add after submitting a ' loading / progress'  indicator that you are waiting an answer of the controller
Now the screen does not show anything and you wonder if your submit actually worked

NB. this slow speed does not happen all the time. But seems behaviour of the CloudkeyGen2 plus

Jan  6 07:42:50 voucher server.sh[46631]: [Web]: /
Jan  6 07:42:51 voucher server.sh[46631]: [Web]: /dist/style.css
Jan  6 07:42:51 voucher server.sh[46631]: [Web]: /images/bg-1.jpg
Jan  6 07:42:51 voucher server.sh[46631]: [Web]: /manifest.json
Jan  6 07:42:51 voucher server.sh[46631]: [Web]: /images/unifi-icon.png
Jan  6 07:42:51 voucher server.sh[46631]: [Web]: /images/favicon.ico
Jan  6 07:43:06 voucher server.sh[46631]: [Web]: /
Jan  6 07:43:21 voucher server.sh[46631]: [Web]: /voucher?code=0000&type=480,0,,,
Jan  6 07:44:41 voucher server.sh[46631]: [Web]: /images/bg-7.jpg
Jan  6 07:44:41 voucher server.sh[46631]: [Web]: /manifest.json

**Comment by glenndehaan** [comment]
Hi,

I forgot that this issue was still open. I have implemented a basic spinner on submit.

Kind regards,
Glenn
