### ISSUE TITLE
tool broken due to new version of Unifi Controller?

### ISSUE THREAD

**Issue by aroundmyroom** [glenndehaan/unifi-voucher-site#27]
Network 8.0.2
version Unifi Controller

Web]: /images/bg-8.jpg
[Web]: /images/unifi-icon.png
[Web]: /dist/style.css
[Web]: /
[Web]: /voucher?code=XXXX&type=480,0,,,
Error while logging in!
AxiosError: Request failed with status code 401
    at settle (/home/unifi-voucher-site/node_modules/axios/dist/node/axios.cjs:1268:12)
    at IncomingMessage.handleStreamEnd (/home/unifi-voucher-site/node_modules/axios/dist/node/axios.cjs:2446:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.1.3',
      'Content-Length': '63',
      'Accept-Encoding': 'gzip, deflate, br',
      [Symbol(defaults)]: [Object]

**Comment by glenndehaan** [comment]
Version 8.0.2 is in early access. And libraries do not have support for version 8 at this moment. Therefore I will close this issue since I only aim to support stable versions

**Comment by aroundmyroom** [comment]
issue was related to the node-unifi part. when the dependency is updated it will be fix (soon) .. I have updated my unifi.js and the tool is working again.
