### ISSUE TITLE
Parameter Single or Multi Use doens't work

### ISSUE THREAD

**Issue by tomcatcw1980** [glenndehaan/unifi-voucher-site#28]
Hi there,

Thank you so much for these projects. I found it yesterday and it helps so much because generating a voucher code via the iOS app is so cumbersome as the menu is so convoluted and hidden.

There is one thing that doesn't quite work, at least for me: single-use or multi-use vouchers value - '0' is for multi-use - '1' it doesn't take. No matter whether I choose 0 or 1, a code is always generated with multi-use.

Could you check this.

Many thanks in advance
Regards
Christian

**Comment by glenndehaan** [comment]
Hi Christian,

You are right this was indeed an issue. I have pushed an update that should resolve this.

Kind regards,
Glenn

**Comment by tomcatcw1980** [comment]
Thank you for your help.
