### ISSUE TITLE
Nice update

### ISSUE THREAD

**Issue by aroundmyroom** [glenndehaan/unifi-voucher-site#33]
Hi Glenn,

nice update .. 
We got some troubles due to MFA and I was struggeling with it and than saw your updates. WOW .. ! compliments !

Maybe you can add in your readme that you need an local account (which you state) with full management access. A user could be confused as Unifi can lock a user to a certain element which is also the hotspot functionality. If that one is enabled the API access is not granted and your tool tells that there is an error creating / syncing the vouchers. so you need to allow full management.
I did not check which part, but I doubt that protect needs to be enabled ;)

Print feature is nice .. but I need a 80mm printer ;) 
What does the 'share' icon do ? It seems for future use, but when clicking it does not do anything (yet) is that correctr?

For future releases I would like to see also an option to see the guest info, who is logged on etc..  but its more a nice to have than a must ;)

Again, thanks for the updates. A happy user !

**Comment by glenndehaan** [comment]
Goodmorning,

Thank you for the nice words. Great to hear that you like the updates.

I have just released a new version that improved the README with your suggestion about the user's role assignment.
In regards to the 'Share' icon I agree this icon was misleading since the functionality is actually copying the code to your clipboard. I this same release I have updated the icon to better reflect that. You can see that it works since there is a small dialog at the bottom of your screen that indicates the copy worked:

<img width="413" alt="afbeelding" src="https://github.com/glenndehaan/unifi-voucher-site/assets/7496187/92e3ae08-60cf-41b3-916c-bf0743408165">

As for your request: I fully understand that this could be interresting to see, I can't promise this will make it in soon. But I will keep this issue open as a reminder ;)

Kind regards,
Glenn

**Comment by aroundmyroom** [comment]
the Copied Code works fine on my desktop, not on my iPhone. That should be harder to accomplish.
Thanks for the icon replacement, makes it more clear what the feature is. 

Keep up the good work!

**Comment by glenndehaan** [comment]
Ahhh iOS ;) yeah this does not surprise me. Looking at the issues online it seems indeed this is impossible to implement correctly.

**Comment by glenndehaan** [comment]
Good Evening,

I have some good news, I have finished the initial implementation for guest information.
An example can be found below:

<img width="1440" alt="afbeelding" src="https://github.com/glenndehaan/unifi-voucher-site/assets/7496187/9fa65c2d-97d5-40a5-8aad-8fee15b2566d">

When updating to the latest release you are now able to click on a voucher and this will open the details and connected guests.

One remark: This only works for 'multi-use' vouchers. For some reason UniFi removes 'single-use' vouchers from the api after they are used. And that means i'm unable to link guests to the original voucher.

Kind regards,
Glenn

**Comment by aroundmyroom** [comment]
Kewl .. As I am always using multi-use this a perfect ;) .. will update soonish .. (now) ;)

**Comment by aroundmyroom** [comment]
![image](https://github.com/glenndehaan/unifi-voucher-site/assets/250108/cd66e08d-80c1-430d-b4d6-ef6682a54ade)

perfect, gives me exact the info I need. to make certain decisions on the vouchers ..

**Comment by aroundmyroom** [comment]
when on a mobile the CSS could get some extra info so that the voucher code is not detected as phonenumber, otherwise you get the question if you want to call that number ;)

**Comment by glenndehaan** [comment]
Great to hear that the feature works. Yeah I saw this issue on my Ipad also. I tried to disable this but it would still generate a link. Will look into this again in the evening to see if I can find a solution for this.

**Comment by glenndehaan** [comment]
I have just released a new version that disabled the pointer-events, hopefully this should disable the click trigger

**Comment by aroundmyroom** [comment]
Looks like I do not have issues on the iphone anymore (just updated as I was on holiday).

Any recommends for a good 80mm printer? ;)

**Comment by glenndehaan** [comment]
Ah great to hear, for a printer I currently do not own one but the person I developed this feature for uses an Epson TM-T20III
