### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by spotityza** [glenndehaan/unifi-voucher-site#34]
Firstly thanks @glenndehaan for this project its great and appreciate all the time you put into this.

Is there any plan to support SSL in the future?

**Comment by glenndehaan** [comment]
Hey Goodmorning,

Thank you for the kind words.
In terms of your question do you SSL termination towards the UniFi controller or for the portal itself?

The connection should already be using SSL but the check for certificates is by default disabled.
When it comes to the portal itself, I do not plan to support this. The reason for this is that when it comes to SSL there are a lot of variables on how someones setup looks like (Using your own certificates, LetsEncrypt, etc.). Therefore I would always recommend using a reverse proxy in front of the portal that handles the SSL termination. Examples could be: Nginx, Apache or Traefik.

Kind regards,
Glenn

**Comment by spotityza** [comment]
Hey @glenndehaan, 

Sorry yes I meant from the portal perspective, we are running locally using reverse proxy to handle, however wanted to check if there was a way to setup for SSL natively. 

Appreciate your response 😄
