### ISSUE TITLE
Font color on voucher creation

### ISSUE THREAD

**Issue by ginlik1996** [glenndehaan/unifi-voucher-site#35]
Hello,

On Chrome and Edge with dark mode enabled, when I try to create a new voucher and I select a Preset voucher type, the text is white on white.

![image](https://github.com/glenndehaan/unifi-voucher-site/assets/60267857/8159eca9-243f-492c-a2e6-52505bef7398)

On Firefox or with light mode enabled, it works as expected.

Thanks

**Comment by glenndehaan** [comment]
Hi @ginlik1996,

Thank you for the report. Indeed on Windows this seems to be a bug.
I just released version 2.6.3 that should address this issue.

Kind regards,
Glenn

**Comment by ginlik1996** [comment]
Works like a charm!
Thanks

Kind reards
Gianluca
