### ISSUE TITLE
problem with "Verifi app"

### ISSUE THREAD

**Issue by CASACONDO** [glenndehaan/unifi-voucher-site#40]
First of all thank you!  i have other of your software up and i got it too in hm and i can access,  but i cannot manage vouchers anf stack on  "sincying vouchers" when it asks me "unifi verify secure app code" that i allow but the app doesnt recognize it 
thank you

**Comment by glenndehaan** [comment]
Hi @CASACONDO ,

Are you able to post some screenshots or logs for me to have a look at. Because i'm unsure what issue you are running into.

**Comment by glenndehaan** [comment]
After reading your message a couple of time. I think I understand your issue, are you saying you setup the app with your UniFi Cloud account. And you are now trying to verify with the UI Verify app as a 2FA step?

If that is the case this is not supported. You should create a local account on the console with "Full Management" access rights and use that within UniFi Voucher Site as explained here: https://github.com/glenndehaan/unifi-voucher-site#prerequisites

**Comment by CASACONDO** [comment]
Ciao Glenn thank you very much, yes I think it doesn’t work for this
verification system
Ok I will try adding a local account and let you to know
Have a wonderful day 🙋🏻‍♂️

Giuseppe Di Filippo



Il giorno lun 30 set 2024 alle 09:37 Glenn de Haan ***@***.***>
ha scritto:

**Comment by CASACONDO** [comment]
I got it with local user 👌🏻 Thank you Giuseppe Di FilippoIl giorno 30 set 2024, alle ore 10:11, Giuseppe Di Filippo ***@***.***> ha scritto:﻿Ciao Glenn thank you very much, yes I think it doesn’t work for this verification system Ok I will try adding a local account and let you to knowHave a wonderful day 🙋🏻‍♂️Giuseppe Di FilippoIl giorno lun 30 set 2024 alle 09:37 Glenn de Haan ***@***.***> ha scritto:
After reading your message a couple of time. I think I understand your issue, are you saying you setup the app with your UniFi Cloud account. And you are now trying to verify with the UI Verify app as a 2FA step?
If that is the case this is not supported. You should create a local account on the console with "Full Management" access rights and use that within UniFi Voucher Site as explained here: https://github.com/glenndehaan/unifi-voucher-site#prerequisites

**Comment by glenndehaan** [comment]
Great to hear. Will close this issue
