### ISSUE TITLE
System gives error: [Auth] Incorrect Configuration Detected!. Authentication is enabled but all authentication services have been disabled

### ISSUE THREAD

**Issue by aroundmyroom** [glenndehaan/unifi-voucher-site#43]
### The problem

AUTH_INTERNAL_ENABLED: 'true'
AUTH_INTERNAL_PASSWORD: '0000'

Are being used, but systems gives incorrect configuration detected. Authentication is enabled but all authentication services have been disabled
if this error happens than there is an error 501
When I enable the OIDC from false to true than I get a web interface
so it seems I am missing something when wanting to use the internal pincode system

### What version of UniFi Voucher Site has the issue?

4.03

### What type of installation are you running?

Development Version (Not Recommended)

**Comment by glenndehaan** [comment]
Hi @aroundmyroom,

I have just released version 4.0.4. It seems that my patch within 4.0.2 for Home Assistant users was breaking the variables for Docker/Development installations. This should now be resolved within this new version.

Kind regards,
Glenn

**Comment by aroundmyroom** [comment]
Thank you.
this new version resolves my issue.
